### ISSUE TITLE
client web / export import configurazione

### ISSUE THREAD

**Issue by tanunebbie** [msimic/mudslinger#5]
se vengono aggiunte delle "stanze favorite" nella fase di export ed import successivo (magari per dover pulire la cache del browser0)0 vengono persi i riferimenti alle stanze, come se non fossero mai state inserite.
Forse non viene esportata.
Ciao Samak

**Comment by msimic** [comment]
Effettivamente non  vengono esportate perche non fanno parte della configurazione del profilo/personaggio.
Un favorito aggiunto al mapper e' un favorito aggiunto accessibile da tutti i personaggi.
Bisognerebbe fare un export dei settings del mapper e import.

**Comment by msimic** [comment]
fatto
