### ISSUE TITLE
Variabile recall per spell castabili

### ISSUE THREAD

**Issue by Jullod** [msimic/mudslinger#6]
a me ha fatto già due o tre volte lo stesso con shield room (modificato)
[12:14]
che tra l'altro anche quando casto normalmente mi considera come lo shield da SO e me lo toglie dal libro come se l'avessi castato

Samak — 24/02/2023 15:46
uhmm allora il pg è wh/th/so, volevo castrami armor e ho sbagliato comando mettendo il + al posto di * ma poi il fatto del true sight l'ha fatto da solo

![recall](https://user-images.githubusercontent.com/126920528/222839535-7028eb3d-2117-4b3d-b000-7262e4a9626f.png)

stesso problema di emidio, però qui non so cosa sia successo. ho scritto per sbaglio cas mete e mi ha registrato dispel m come recall
[15:23]
ora se uso alias disp me lo casta di recall in automatico

**Comment by msimic** [comment]
se usi "cas"  o "+" per castare o un alias del mud (e non alias cast del client) allora il client non ricorda cosa hai castato per ultimo perche non gli passa per i suoi alias, e quando viene che "devi usare recall " mette l'ultimo spell che ha ricordato chehai castato, che era il dispel magic (probabilmente via  alias "disp")

bisognera cambiare un po di cose per fixxare sta cosa...

**Comment by msimic** [comment]
dalla prox versione mud dovrebbe andare
