### ISSUE TITLE
Buffer non scrollabili in webkit/iPadOS

### ISSUE THREAD

**Issue by lpian24** [msimic/mudslinger#7]
Nessun buffer - ne’ il principale ne’ i secondari come il grouptell o i tell - sono scrollabili, sia con mouse sia con touchscreen

**Comment by msimic** [comment]
ok cerchero' di capire, ma non so quanto sara facile in quanto non ho un iPad per provare

**Comment by lpian24** [comment]
Risolto usando temporasanguinis.it/client anzichè passare dal link della home
