### ISSUE TITLE
Ridimensionamento buffer principale su combat (Webkit/iPadOS)

### ISSUE THREAD

**Issue by lpian24** [msimic/mudslinger#8]
Il buffer principale, che normalmente va a capo correttamente alla larghezza del buffer, all’inizio di ogni combattimento viene ridimensionato andando in parte a scomparire sotto i buffer secondari/mapper.

Presumo venga ridimensionato seguendo il prompt che normalmente sta nella larghezza della finestra e durante i combat, con nome/stato diventa più lungo.

**Comment by msimic** [comment]
potresti darmi qualche screenshot per piacere?
mi e' difficile da capire cosa succede
